





export {
  ensureClientFingerprintReady,
  type EnsureClientFingerprintReadyOptions,
  type EnsureClientFingerprintReadyResult,
} from './FingerprintClientIdentityService.js';

export {
  FingerprintDataService,
  FINGERPRINT_DATA_PLANE_CONTRACT,
  resolveFingerprintDataPlaneAvailability,
  type FingerprintDataPlaneAvailability,
  type FingerprintDataPlaneHealth,
  type FingerprintDataPlaneSource,
  type FingerprintRecord,
} from './FingerprintDataService.js';

export {
  enrichFingerprint,
  enrichFingerprintOnSessionCreate,
  enrichFingerprintOnValidation,
  enrichFingerprintOnMismatch,
  getEnrichmentServiceHealth,
  classifyDevice,
  maskIpAddress,
  parseUserAgent,
  type ConsentPreferenceData,
  type FingerprintAdditionalAttributes,
  type FingerprintEnrichmentOptions,
  type FingerprintRequestContext,
  type EnrichedFingerprint,
} from './FingerprintEnrichmentService.js';

export {
  FingerprintHistoryService,
  calculateDistance,
  isImpossibleTravel,
  type FingerprintHistory,
  type FingerprintInvestigationWindow,
  type FingerprintSecuritySignal,
  type FingerprintSecurityInvestigation,
  type LocationChange,
  type FingerprintChange,
  type UserActivitySummary,
} from './FingerprintHistoryService.js';

export {
  FingerprintSearchService,
  type SearchFilters,
  type SearchServiceResult,
  type SearchResults,
  type ServiceSearchFacets,
  type ServiceQuickSearchResult,
  type ExportResult,
} from './FingerprintSearchService.js';

export {
  applyFingerprintOverlayHydrationState,
  restoreFingerprintOverlayServerState,
  getFingerprintSettingsHistory,
  recoverFingerprintSettingsFromTempo,
  deriveFingerprintOverlayHydrationState,
  hasTempoBackedSettings,
  isTempoUnavailableError,
  buildFingerprintOverlayFallbackKey,
  writeFingerprintOverlayFallback,
  readFingerprintOverlayFallback,
  createFingerprintOverlaySyncRuntime,
  createFingerprintOverlayRuntime,
  buildFingerprintOverlaySyncAttributes,
  fetchFingerprintSettingsHistoryFromApi,
  resolveFingerprintOverlayClientState,
  syncFingerprintOverlayChanges,
  DEFAULT_TEMPO_RETRY_AFTER_MS,
  DEFAULT_TEMPO_RECOVERY_MAX_RETRIES,
  DEFAULT_OVERLAY_BATCH_INTERVAL_MS,
  DEFAULT_OVERLAY_FALLBACK_KEY_PREFIX,
  DEFAULT_OVERLAY_HISTORY_ENDPOINT,
  DEFAULT_OVERLAY_SYNC_ENDPOINT,
  type FingerprintOverlayServerState,
  type FingerprintOverlayChangeSource,
  type FingerprintOverlayChange,
  type FingerprintOverlayFallbackEntry,
  type FingerprintOverlayStorageAdapter,
  type FingerprintOverlaySyncRequest,
  type FingerprintOverlaySyncResponse,
  type SyncFingerprintOverlayChangesOptions,
  type FingerprintOverlaySyncAttributeValue,
  type FingerprintOverlaySyncAttributes,
  type FingerprintOverlayFetchResponse,
  type FingerprintOverlayFetch,
  type FingerprintOverlayJsonFetchResponse,
  type FingerprintOverlayJsonFetch,
  type FingerprintOverlaySyncRuntimeOptions,
  type FingerprintOverlaySyncRuntime,
  type FingerprintOverlayRuntimeState,
  type FingerprintOverlayRuntimeOptions,
  type FingerprintOverlayRuntimePatch,
  type FingerprintOverlayRuntime,
  type FingerprintSettingsHistoryKey,
  type FingerprintSettingsHistoryOptions,
  type FingerprintSettingsHistoryEntry,
  type TempoRecoveryOptions,
  type TempoRecoveryResult,
  type FingerprintOverlayHydrationState,
  type FingerprintOverlaySettingsSnapshot,
  type ApplyFingerprintOverlayHydrationStateOptions,
  type AppliedFingerprintOverlayHydrationState,
  type ResolveFingerprintOverlayClientStateOptions,
  type ResolvedFingerprintOverlayClientState,
} from './FingerprintOverlayRuntimeService.js';

export {
  restoreFingerprintSettings,
  restoreFullSettings,
  getFingerprintVisitCount,
  getTimeSinceLastVisit,
  formatTimeSinceLastVisit,
  hasPreviousConsent,
  getVisitHistory,
  getSettingsHistory,
  isSupportedSettingsHistoryKey,
  getDefaultSettings,
  SUPPORTED_SETTINGS_HISTORY_KEYS,
  type FingerprintSettings,
  type VisitSummary,
  type SupportedSettingsHistoryKey,
  type SettingsHistoryEntry,
  type SettingsHistoryOptions,
} from './FingerprintSettingsService.js';
